version: '3'

services:

 openresty:
  image: openresty/openresty:1.19.3.1-alpine
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./shence.conf:/etc/nginx/conf.d/shence.conf:ro
   - ./simple-url-shorten:/usr/local/openresty/lualib/short:ro
  container_name: shence_url_shorten